// Repository creation, cloning, and the one-time Unreal project setup
// (.loreignore + raised store cap) that keeps big engine projects pushable.

use super::process::run_lore;

/// Create a new repository in `path`, registered on the server given by `url`
/// (e.g. "lore://127.0.0.1:41337/my-project"). The folder gets a `.lore` tree.
/// Needs a reachable Lore server, or lore reports a connection error.
#[tauri::command(async)]
pub fn lore_create_repo(path: String, url: String) -> Result<String, String> {
    if url.trim().is_empty() {
        return Err("Type the server address, like lore://127.0.0.1:41337/my-project".to_string());
    }
    let dir = std::path::Path::new(&path);
    if !dir.is_dir() {
        return Err("Pick a folder first.".to_string());
    }
    if dir.join(".lore").is_dir() {
        return Err("That folder is already a Lore project.".to_string());
    }
    let out = run_lore(&path, &["repository", "create", url.trim()])?;
    // Set the new repo up for Unreal before the first scan/commit ever runs.
    apply_unreal_setup(dir);
    Ok(out)
}

/// When the folder is an Unreal project, make it usable for Unreal: raise the
/// tiny default local store cap (so large file fragments are not evicted before
/// they can be pushed - the documented cause of "Missing fragments"), and drop in
/// a `.loreignore` so the huge derived folders are never scanned/staged/committed.
/// Idempotent and Unreal-only: does nothing for a non-Unreal folder, never
/// clobbers an existing `.loreignore`, and only bumps the store cap if it is
/// still the default. Returns true if it just created the `.loreignore`.
fn apply_unreal_setup(dir: &std::path::Path) -> bool {
    if !has_uproject(dir) {
        return false;
    }
    raise_store_capacity(&dir.join(".lore").join("config.toml"));
    let ignore = dir.join(".loreignore");
    let added = !ignore.exists();
    write_unreal_loreignore(&ignore);
    added
}

/// Ensure an already-existing Unreal project is set up (called when a project is
/// opened, not just created). Returns true if a `.loreignore` was just added, so
/// the UI can mention it.
#[tauri::command(async)]
pub fn ensure_unreal_setup(repo: String) -> Result<bool, String> {
    Ok(apply_unreal_setup(std::path::Path::new(&repo)))
}

/// True if the folder holds an Unreal project file (`*.uproject`).
fn has_uproject(dir: &std::path::Path) -> bool {
    let Ok(entries) = std::fs::read_dir(dir) else { return false };
    entries.flatten().any(|e| {
        e.path()
            .extension()
            .and_then(|x| x.to_str())
            .is_some_and(|x| x.eq_ignore_ascii_case("uproject"))
    })
}

/// Bump the local immutable store cap so big projects' fragments survive until
/// push. Lore's default is only 10 MiB with a 10s eviction delay; we replace the
/// known defaults with generous values. Best-effort - if the file looks
/// different we leave it untouched rather than risk corrupting it.
fn raise_store_capacity(config: &std::path::Path) {
    let Ok(text) = std::fs::read_to_string(config) else { return };
    // 8 GiB cap, 5 min eviction delay - comfortably covers an Unreal Content push.
    let patched = text
        .replace("max_capacity = 10485760", "max_capacity = 8589934592")
        .replace("eviction_delay = 10", "eviction_delay = 300");
    if patched != text {
        let _ = std::fs::write(config, patched);
    }
}

/// Write a `.loreignore` for an Unreal project. Uses std::fs::write so the file
/// has NO byte-order mark - a BOM corrupts the first ignore line. Never clobbers
/// a `.loreignore` the user already made.
fn write_unreal_loreignore(path: &std::path::Path) {
    if path.exists() {
        return;
    }
    // Derived/transient Unreal folders - regenerated by the engine, never source.
    let body = "# Unreal Engine - generated by lore-ui. These are regenerated by the\n\
        # engine and must not be versioned. Source lives in Content/ Config/ Source/.\n\
        Binaries/\n\
        Build/\n\
        DerivedDataCache/\n\
        Intermediate/\n\
        Saved/\n\
        .vs/\n\
        .idea/\n\
        *.sln\n\
        *.suo\n\
        *.xcodeproj/\n\
        *.xcworkspace/\n";
    let _ = std::fs::write(path, body);
}

/// Clone an existing repository from any Lore server URL into a new subfolder of
/// `parent`. The server can be anywhere reachable - localhost, a LAN box, a VPS,
/// a Tailscale 100.x peer - it is just a `lore://host:port/name` URL. Returns the
/// path of the cloned folder so the UI can open it.
#[tauri::command(async)]
pub fn lore_clone(url: String, parent: String) -> Result<String, String> {
    if url.trim().is_empty() {
        return Err("Type the repository URL, like lore://host:port/name".to_string());
    }
    let p = std::path::Path::new(&parent);
    if !p.is_dir() {
        return Err("Pick a folder to clone into.".to_string());
    }
    // Land the repo in a subfolder named after it (the last URL segment), so we
    // never clone into a folder that already has contents.
    let name = url
        .trim()
        .trim_end_matches('/')
        .rsplit('/')
        .next()
        .filter(|s| !s.is_empty())
        .unwrap_or("cloned-repo");
    let dest = p.join(name);
    if dest.join(".lore").is_dir() {
        return Err(format!("\"{name}\" is already cloned in this folder."));
    }
    run_lore(&parent, &["clone", url.trim(), &dest.to_string_lossy()])?;
    // Hand back the cloned path so the caller can open it straight away.
    Ok(dest.to_string_lossy().to_string())
}
